# Generated by Django 4.2.1 on 2023-06-08 18:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('memory_feature', '0002_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f9ed3bac-f2f7-415a-b9a9-60a7e5364d2f'), editable=False, unique=True),
        ),
    ]
