# Generated by Django 4.2.1 on 2023-06-08 18:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('memory_feature', '0003_alter_user_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memory',
            old_name='uuid',
            new_name='muid',
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b60dac6b-abe8-4f8d-bc60-d2f7007a9bc1'), editable=False, unique=True),
        ),
    ]
